# Copyright (c) 2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.
#
# NVIDIA CORPORATION & AFFILIATES and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION & AFFILIATES is strictly prohibited.

# On Towaki's machine with a RTX8000 on the V8, this code takes:
# 3 seconds per epoch
# 2:20 script runtime as reported on tensorboard
# 27.8 PSNR 0.9295 SSIM 0.0988 LPIPS at the final validation

global:
    exp_name: 'test-ngp-nerf'

optimizer:
    optimizer_type: 'rmsprop'
    lr: 0.001

dataset:
    multiview_dataset_format: 'rtmv'
    num_rays_sampled_per_img: 4096
    mip: 3
    bg_color: 'white'

tracer:
    raymarch_type: 'ray'
    num_steps: 1024

renderer:
    #render_batch: 4000
    render_batch: 0
    camera_origin:
        - -3.0
        - 0.65
        - -3.0
    render_res:
        - 1024
        - 1024

trainer:
    epochs: 50
    batch_size: 1
    model_format: 'full'
    valid_every: 50
    save_every: 10
    prune_every: -1

grid:
    grid_type: 'HashGrid'
    interpolation_type: 'linear'
    multiscale_type: 'cat'
    feature_dim: 2
    feature_std: 0.01
    feature_bias: 0.0
    num_lods: 16
    tree_type: 'geometric'
    min_grid_res: 16
    max_grid_res: 2048
    codebook_bitwidth: 19
    blas_level: 7

nef:
    hidden_dim: 64
    num_layers: 1
    pos_embedder: 'none'
    position_input: False
    view_embedder: 'positional'
    view_multires: 4
    pretrained: '/home/salar/RVL/repos/kaolin-wisp/_results/logs/runs/v8_ngp_NEW_mip3_noprune/20230122-224649/model.pth'

validation:
    valid_only: True